# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bfe2df00c7fe8341d22fe4def45338cdc533e9fc4f489daac047ba62d7a1415d7bcbc13b82a77d6e76b21ba5639c3d34c4f52ab0af0fa73b56ef955898ec757a

test:
  secret_key_base: 011f5efa941eb32a8a8b2e2c79db89bbf7238fd4e8c671cdbef606dae47c94e8c9e3c6b017c9cce66b205b1a6bd05b2f8c79c48d9ed6bf01d3cdebc8d656260a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
